import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Nav from "@/Components/Nav";
import Footer from "@/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cart-Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* 
        CHANGED: Changed 'min-h-full' to 'min-h-screen' to accurately 
        measure the device viewport height. Keep flex and flex-col.
      */}
      <body className="min-h-screen flex flex-col">

        <Nav></Nav>
        
        {/* 
          CHANGED: Added 'flex-1' so this main container grows 
          to push the footer down on short pages.
        */}
        <main className="flex-1">
          {children}
          <Toaster></Toaster>
        </main>
        
        <Footer></Footer>
        
      </body>
    </html>
  );
}